language: python
python:
  - "2.7"

before_script:
  - openssl aes-256-cbc -K $encrypted_a200a99e607c_key -iv $encrypted_a200a99e607c_iv -in HelloWorld.txt.enc -out HelloWorld.txt -d
script:
  - cat HelloWorld.txt
